ques=["What is artitifical intelligence? What is its scope in the market for engineering students?",
"Why should I choose Artificial Intelligence training?",
"What is the future scope of Artificial Intelligence training in intelligent domain?",
"Why should I choose LIVEWIRE for training purpose?", 
"Why Artificial Intelligence is preferred?",
"What is the future of the students after they are trained in Artifiicial Intelligence?",
"What do I gain in the field of Artificial Intelligence through the training in LIVEWIRE?",
"Will I get a valid Certificate after the completion of Course in LIVEWIRE?",
"What is the specialty about LIVEWIRE?",
"What is the outcome of the Artificial Intelligence training?",
"Will I get enough attention from the trainers?",
"Where do I get placement, if I finish Artificial Intelligence training?",
"Are the classes common for all students?",
"Is “Hands on training” available for Artificial Intelligence training?",
"I am a fresher completing my degree. How will you guide me to build my career?",
"Can I do the individual project of my own after completion of this Artificial Intelligence course?",
"Why should I choose a Master Program?",
"Why should I choose a Diploma Program?",
"What is the Job roles / Opportunity for a Fresher?",
"Only a computer science engineer can learn this? Who can learn this course?"
]
